# Generated by Django 3.1.1 on 2020-09-27 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_model', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('Processor', models.CharField(max_length=64)),
                ('RAM', models.CharField(max_length=64)),
                ('Storage', models.CharField(max_length=64)),
                ('Display', models.CharField(max_length=64)),
                ('Camera', models.CharField(max_length=64)),
                ('admin_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
